routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('blog/home');
// });


Route::get('/', 'PostController@publicHome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('posts', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Auth;       
use Illuminate\Http\Request;

class PostController extends Controller
{

    public function publicHome(){
        $posts = Post::paginate(6);

        return view('blog/home', ['posts'=>$posts]);
    }   
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $loggedInUserId =  Auth::id();
        $posts = Post::all()->where('user_id', $loggedInUserId);
       
        return view('adminPanel/home', ['posts'=>$posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adminPanel/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = new Post;
        $postTitle = $request->title;
        $postBody = $request->body;  
        //$post->user_id = Auth::user()->id;
        $postUserId = Auth::id(); 

        $post->user_id = $postUserId;
        $post->title = $postTitle;
        $post->body = $postBody;

        $post->save();

        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $post = Post::find($id);

         $data = array(
             'id' => $id,
             'post'=> $post
         );

         return view('blog.viewPost' ,$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);

        return view('adminPanel.edit', ['post'=>$post]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::find($id);

        if (isset($request->title)){
            $post->title = $request->title;
        }

        if (isset($request->body)){
            $post->body = $request->body;
        }

        $post->save();

        if (isset($request->editForm)){
            return redirect()->route('posts.index');
        }else{
           return redirect()->route('posts.show', ['id'=>$id]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);

        $post->delete();

        return redirect()->route('posts.index');
    }
}

resources/views/adminPanel/create.blade.php
@extends('layouts.template')

@section('title', 'Add New Post')

@section('content')


<div class="container">
    
    <form action="{{ route('posts.store') }}" method="POST" role="form">
        {{ csrf_field() }}
        <legend>Add New Post</legend>
    
        <div class="form-group">
            <label for="">Title:</label>
            <input type="text" class="form-control" name="title" id="" placeholder="Input field">
        </div>

        <div class="form-group">
            <label for="">Content:</label>
            <textarea class="form-control" name="body" id="" placeholder="Input field"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        
        <a class="btn btn-warning" href="{{ route('posts.index')}}" role="button">Go back</a>
        
    </form>
    
</div>


@endsection()

resources/views/adminPanel/edit.blade.php
@extends('layouts.template')

@section('title', 'Edit Post #' . $post->id)

@section('content')


<div class="container">
    
    <form action="{{ route('posts.update', ['id'=>$post->id]) }}" method="POST" role="form">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="PUT">
        
        <legend>Edit Post # {{ $post->id }}</legend>
    
        <div class="form-group">
            <label for="">Title:</label>
            <input type="text" class="form-control" name="title" id="" placeholder="Input field" value="{{ $post->title }}">
        </div>

        <div class="form-group">
            <label for="">Content:</label>
            <textarea class="form-control" name="body" id="" placeholder="Input field">{{ $post->body }}</textarea>
        </div>

        <input type="hidden" name="editForm" value="editForm">
        <button type="submit" class="btn btn-primary">Submit</button>
        
        <a class="btn btn-warning" href="{{ route('posts.index')}}" role="button">Go back</a>
        
    </form>
    
</div>


@endsection()

resources/views/adminPanel/home.blade.php
@extends('layouts.template')

@section('title', 'Manage Post Admin')


@section('content')

<div class="container">
  <h1 class="m-3">Admin Panel</h1>
    <a href="{{ route('posts.create') }}" class="btn btn-sm btn-primary float-right m-3">Add new blog post</a><br>
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Content</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
        @foreach($posts as $post)
            <tr>
                <td>{{ $post->id  }}</td>
                <td>{{ $post->title  }}</td>
                <td>{{ $post->body  }}</td>
                <td>
                   <a class="btn btn-sm btn-warning" href="{{ route('posts.edit',['id'=>$post->id]) }}" role="button">Edit Post</a>    
                </td>
                <td>
                    <form action="{{ route('posts.destroy', ['id'=>$post->id]) }}" method="post">
                    {{ csrf_field() }}
                        <input type="hidden" name="_method" value="DELETE">
                        <input class="btn btn-sm btn-danger" type="submit" value="Delete">
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
</div>
@endsection

resources/views/blog/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>The LRMG Blog</h1>
        <div class="row">  
            @foreach($posts as $post)
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="p-3 mb-2 bg-primary text-white">
                            <h2>{{ $post->title }}</h2>
                            <hr>
                            <h6><strong>Post Created At:</strong> {{ date('F d, Y', strtotime($post->created_at)) }}</h6>
                            <p>{{ $post->body }}</p>
                            <a class="btn btn-sm btn-warning" href="{{ route('posts.show',['id'=>$post->id]) }}" role="button">View all</a>    
                        </div>
                </div>
            @endforeach    
        
        </div>
        <div class="text-center">{{ $posts->links() }}</div>
    </div>
@endsection

resources/views/blog/viewPost.blade.php
@extends('layouts.publicHomePageTemplate')

@section('title', 'View Post #' . $id)
  
@section('content')   

<div class="container">
    <h2>{{ $post->title  }}</h2>
    <h6><strong>Post Created At:</strong> {{ date('F d, Y', strtotime($post->created_at)) }}</h6>
    <p>{{ $post->body }}</p>    
    <a class="btn btn-sm btn-primary" href="{{ url('/') }}" role="button">Back to home</a>
       
</div>

    
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <img src="http://lrmg.co.za/assets/images/LRMG_performance_agency/logo.png" alt="logo">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest              
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li><a class="nav-link" href="{{ route('posts.index') }}">Manage posts</a></li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/publicHomePageTemplate.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <h1>@yield('title')</h1>
  
  <div class="row">
      
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="p-3 mb-2 bg-dark text-white">
                <h2>Post 1</h2>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt dicta dignissimos nam inventore aut? Facere dolor voluptatum magni deleniti nulla quasi laboriosam animi et officia repellat sunt enim, aperiam recusandae.</p>     
            </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="p-3 mb-2 bg-dark text-white">
                <h2>Post 2</h2>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt dicta dignissimos nam inventore aut? Facere dolor voluptatum magni deleniti nulla quasi laboriosam animi et officia repellat sunt enim, aperiam recusandae.</p>     
            </div>
      </div>
      
  </div>
  
</div>
@endsection

resources/views/layouts/template.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
            <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        <img src="http://lrmg.co.za/assets/images/LRMG_performance_agency/logo.png" alt="logo">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">
                            
                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @guest              
                                <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                                <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                            @else
                                <li><a class="nav-link" href="{{ route('posts.index') }}">Manage posts</a></li>
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }} <span class="caret"></span>
                                    </a>

                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>   
        <div class="container">
            @yield('content')                         
        </div>
    </div>
</body>
</html>